version: "3.9"

services:

  client:
    build: ./client
    environment:
      KAFKAJS_NO_PARTITIONER_WARNING: 1
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: my-client
    volumes:
      - ./client/src:/app/src
    ports:
      - 80:3000
    entrypoint: ["npm", "run", "dev"]
    depends_on:
      - kafka

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      KAFKA_CFG_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

